RESOURCES= \
res/1_route.png \
res/2_route.png \
res/3_route.png \
res/77001_index.wdf \
res/Arrow.png \
res/Bubble_01.png \
res/Bubble_02.png \
res/CrossHair.png \
res/Departure.png \
res/Destination.png \
res/Header_Black_Mid.png \
res/Header_Black_left.png \
res/Header_Black_right.png \
res/Info.png \
res/LOL-female.png \
res/LOL.png \
res/On_map_anonymous.png \
res/On_map_nickname.png \
res/PointerComment.png \
res/PointerMenu.png \
res/RT0Stars.png \
res/RT1Star.png \
res/RT2Stars.png \
res/RT3Stars.png \
res/RT4Stars.png \
res/RT5Stars.png \
res/SUV.png \
res/SearchBox_left.png \
res/SearchBox_middle.png \
res/SearchBox_right.png \
res/Selection.png \
res/TS_top_mood_baby.png \
res/Tweeter-logo.png \
res/Txtbox_left.png \
res/Txtbox_left_selected.png \
res/Txtbox_middle.png \
res/Txtbox_middle_selected.png \
res/Txtbox_right.png \
res/Txtbox_right_selected.png \
res/about.png \
res/alert_icon_accident.png \
res/alert_icon_addon_comment.png \
res/alert_icon_addon_twitter.png \
res/alert_icon_addon_user.png \
res/alert_icon_addon_waze.png \
res/alert_icon_chit_chat.png \
res/alert_icon_hazard.png \
res/alert_icon_other.png \
res/alert_icon_police.png \
res/alert_icon_road_construction.png \
res/alert_icon_traffic_info.png \
res/alert_icon_traffic_jam.png \
res/alert_marker_small.png \
res/alert_pin_accident.png \
res/alert_pin_addon_attachment.png \
res/alert_pin_addon_comment.png \
res/alert_pin_addon_twitter.png \
res/alert_pin_chit_chat.png \
res/alert_pin_hazard.png \
res/alert_pin_loads.png \
res/alert_pin_other.png \
res/alert_pin_parking.png \
res/alert_pin_police.png \
res/alert_pin_road_construction.png \
res/alerts.menu \
res/alerts_offline.menu \
res/all.png \
res/all_routes.png \
res/attachment.png \
res/attachment_white.png \
res/battery_0.png \
res/battery_1.png \
res/battery_2.png \
res/battery_3.png \
res/battery_4.png \
res/battery_charging.png \
res/beetle.png \
res/border_black_bottom.png \
res/border_black_bottom_left.png \
res/border_black_bottom_no_frame.png \
res/border_black_bottom_right.png \
res/border_black_left.png \
res/border_black_right.png \
res/border_black_top.png \
res/border_black_top_left.png \
res/border_black_top_right.png \
res/border_white_bottom.png \
res/border_white_bottom_left.png \
res/border_white_bottom_right.png \
res/border_white_left.png \
res/border_white_right.png \
res/border_white_top.png \
res/border_white_top_left.png \
res/border_white_top_right.png \
res/bored-female.png \
res/bored.png \
res/bottom_bar_background.png \
res/bus.png \
res/busy-female.png \
res/busy.png \
res/button_down.png \
res/button_image_attachment_down.png \
res/button_image_attachment_up.png \
res/button_meters.png \
res/button_miles.png \
res/button_up.png \
res/car_blue.png \
res/car_gray.png \
res/car_green.png \
res/car_race.png \
res/car_red.png \
res/car_yellow.png \
res/checkbox_off.png \
res/checkbox_on.png \
res/compass_bg.png \
res/container_bg.png \
res/container_bg_night.png \
res/context_menu_popup_left.png \
res/context_menu_popup_right.png \
res/cool-female.png \
res/cool.png \
res/crown.png \
res/cursor.png \
res/default_checkbox_off.png \
res/default_checkbox_on.png \
res/detectreceiver.png \
res/edit_left.png \
res/edit_right.png \
res/editor_bar_bg.png \
res/empty_image.png \
res/empty_image_small.png \
res/facebook_connect.png \
res/facebook_default_image.png \
res/facebook_default_image_small.png \
res/facebook_disconnect.png \
res/facebook_settings.png \
res/favorite.png \
res/foursquare.png \
res/foursquare_checkin.png \
res/foursquare_checkin_focus_heb.png \
res/foursquare_logo.png \
res/general_settings.png \
res/groups_default_icons.png \
res/happy-female.png \
res/happy.png \
res/header.png \
res/help.png \
res/help_menu.png \
res/history.png \
res/home.png \
res/in_a_hurry-female.png \
res/in_a_hurry.png \
res/inlove-female.png \
res/inlove.png \
res/lang.conf \
res/location.png \
res/login_details.png \
res/ls_icon_generic.png \
res/ls_icon_google.png \
res/ls_logo_generic.png \
res/ls_logo_google.png \
res/mad-female.png \
res/mad.png \
res/map_error.png \
res/map_error_focus_heb.png \
res/map_error_small.png \
res/map_updates.menu \
res/map_updates_menu.png \
res/map_updates_menu_focus_heb.png \
res/mark_location.png \
res/mark_location_pin.png \
res/marked_location.png \
res/menu_bg_bottom.png \
res/menu_bg_middle.png \
res/menu_bg_top.png \
res/more.menu \
res/motorbike.png \
res/mydirection.png \
res/mydirection_focus_heb.png \
res/nav_approaching.png \
res/nav_bar_address.png \
res/nav_bar_direction_small.png \
res/nav_bar_direction_tall.png \
res/nav_bar_eta.png \
res/nav_continue.png \
res/nav_exit_left.png \
res/nav_exit_right.png \
res/nav_keep_left.png \
res/nav_keep_right.png \
res/nav_roundabout_e.png \
res/nav_roundabout_l.png \
res/nav_roundabout_r.png \
res/nav_roundabout_s.png \
res/nav_roundabout_u.png \
res/nav_turn_left.png \
res/nav_turn_right.png \
res/nav_u_turn.png \
res/navigation_list.png \
res/new_alert_marker.png \
res/next_e.png \
res/next_s.png \
res/north.png \
res/north_off.png \
res/north_touch.png \
res/objects \
res/objects_touch \
res/objects_wide \
res/objects_wide_touch \
res/oppositedirection.png \
res/oppositedirection_focus_heb.png \
res/orange_tag.png \
res/pacman1.png \
res/pacman2.png \
res/pacman3.png \
res/pacman4.png \
res/pacman5.png \
res/peaceful-female.png \
res/peaceful.png \
res/points_dot.png \
res/previous_e.png \
res/previous_s.png \
res/privacy_anonymous.png \
res/privacy_invisible.png \
res/privacy_nickname.png \
res/privacy_settings.png \
res/progress_filled.png \
res/progress_left.png \
res/progress_left_fill.png \
res/progress_middle.png \
res/progress_right.png \
res/progress_right_fill.png \
res/progress_wazzy.png \
res/prompt_list.txt \
res/question.png \
res/quick.menu \
res/quit.png \
res/real_time_alerts_list.png \
res/real_time_police_alert.png \
res/recommend_waze.png \
res/red_ferrari.png \
res/red_marker_small.png \
res/red_tag.png \
res/redlightcam_focus_heb.png \
res/report_list.menu \
res/reportaccident.png \
res/reportaccident_focus_heb.png \
res/reporthazard.png \
res/reporthazard_focus_heb.png \
res/reportincident.png \
res/reportincident_focus_heb.png \
res/reportother_focus_heb.png \
res/reportparking.png \
res/reportparking_focus_heb.png \
res/reportpolice.png \
res/reportpolice_focus_heb.png \
res/reporttrafficjam.png \
res/reporttrafficjam_focus_heb.png \
res/response_bubble1.png \
res/response_bubble2.png \
res/rm_dummy_speed_cam.png \
res/rm_speed_cam.png \
res/rm_zoomin.png \
res/rm_zoomout.png \
res/road_construction.png \
res/road_construction_focus_heb.png \
res/road_roller01.png \
res/road_roller02.png \
res/road_roller03.png \
res/round_checkbox_checked.png \
res/round_checkbox_unchecked.png \
res/sad-female.png \
res/sad.png \
res/save_location.png \
res/schema.png \
res/schema1.png \
res/schema2.png \
res/schema3.png \
res/schema4.png \
res/schema5.png \
res/schema6.png \
res/schema_j2me \
res/search.menu \
res/search_address.png \
res/search_favorites.png \
res/search_history.png \
res/search_icon.png \
res/search_marked_locations.png \
res/search_menu.png \
res/setasdeparture.png \
res/setasdestination.png \
res/settings.menu \
res/settingsmenu.png \
res/show_shortcuts.png \
res/singing-female.png \
res/singing.png \
res/sleepy-female.png \
res/sleepy.png \
res/smart.png \
res/speed_cam_alert.png \
res/speed_cam_warn.png \
res/speedcam.png \
res/speedcam_focus_heb.png \
res/speedometer.png \
res/speedy-female.png \
res/speedy.png \
res/splash_sound_off.png \
res/splash_sound_on.png \
res/sprites \
res/starving-female.png \
res/starving.png \
res/stop_navigate.png \
res/submit_logs.png \
res/sword.png \
res/tab_left.png \
res/tab_left_disabled.png \
res/tab_not_selected_left.png \
res/tab_not_selected_middle.png \
res/tab_not_selected_right.png \
res/tab_right.png \
res/tab_right_disabled.png \
res/tab_selected_left.png \
res/tab_selected_middle.png \
res/tab_selected_right.png \
res/taxi.png \
res/ticker_divider.png \
res/ticker_middle.png \
res/togglenewroads.png \
res/togglenewroads_focus_heb.png \
res/top_alerts.png \
res/top_bar \
res/top_bar_background.png \
res/top_connected.png \
res/top_logo.png \
res/top_mood_LOL.png \
res/top_mood_baby.png \
res/top_mood_bored.png \
res/top_mood_bronze.png \
res/top_mood_busy.png \
res/top_mood_cool.png \
res/top_mood_crown.png \
res/top_mood_disabled.png \
res/top_mood_gold.png \
res/top_mood_happy.png \
res/top_mood_in_a_hurry.png \
res/top_mood_inlove.png \
res/top_mood_mad.png \
res/top_mood_peaceful.png \
res/top_mood_peaceful2.png \
res/top_mood_sad.png \
res/top_mood_shield.png \
res/top_mood_silver.png \
res/top_mood_singing.png \
res/top_mood_sleepy.png \
res/top_mood_speedy.png \
res/top_mood_starving.png \
res/top_mood_sword.png \
res/top_mood_wondering.png \
res/top_mute.png \
res/top_not_connected.png \
res/top_privacy_anonymous.png \
res/top_privacy_invisible.png \
res/top_privacy_nickname.png \
res/top_privacy_offline.png \
res/top_responses.png \
res/top_satellite_off.png \
res/top_satellite_on.png \
res/top_satellite_poor.png \
res/traffic.png \
res/treasure_chest.png \
res/twitter_logo.png \
res/twitter_small_icon.png \
res/update_map_button.png \
res/update_map_button_recording.png \
res/updaterange.png \
res/updaterange_focus_heb.png \
res/waze.png \
res/waze_logo.png \
res/waze_selected.png \
res/wazer_FB.png \
res/wazer_baby.png \
res/wazer_bronze.png \
res/wazer_crown_ping.png \
res/wazer_gold.png \
res/wazer_ping.png \
res/wazer_shield_ping.png \
res/wazer_silver.png \
res/wazer_sword_ping.png \
res/wazzy1.png \
res/wazzy2.png \
res/wazzy3.png \
res/wazzy4.png \
res/welcome.png \
res/welcome_wide.png \
res/wondering-female.png \
res/wondering.png \
res/work.png \
res/yellow_tag.png \
res/program.data.bin \
